FROM davisvansant/alpine-base

ONBUILD RUN apk add --no-cache --virtual .build-deps \
  # coreutils \
  # make \
  zlib-dev \
  openssl-dev \
  openssl \
  # gcc \
  linux-headers \
  build-base \
  libxml2-dev \
  libxslt-dev
